// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD-790_IAGocFY3S6ySpqJ4mX9ZdEsCHA',
    appId: '1:594368309909:web:2774af8e82640f637c899c',
    messagingSenderId: '594368309909',
    projectId: 'fir-practice-app-eec08',
    authDomain: 'fir-practice-app-eec08.firebaseapp.com',
    storageBucket: 'fir-practice-app-eec08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfBBgjn_7BBr6kqpLxMBjsKFPBptsIXSo',
    appId: '1:594368309909:android:86e6d65726dc1cdc7c899c',
    messagingSenderId: '594368309909',
    projectId: 'fir-practice-app-eec08',
    storageBucket: 'fir-practice-app-eec08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzr5TXSLVAKsp_sQz-snfzGtPbbC_13pI',
    appId: '1:594368309909:ios:43ad0ecbda6951957c899c',
    messagingSenderId: '594368309909',
    projectId: 'fir-practice-app-eec08',
    storageBucket: 'fir-practice-app-eec08.appspot.com',
    iosBundleId: 'com.example.simpleApp',
  );
}
